### PR TITLE
Initial population of README

### PR DESCRIPTION
**Pull request by gtvj**
This sets out the purpose of the repository and some proposals for ways of working. Please let me know if you're happy with it and/or if you'd like there to be any changes. 

Please let me know before 5pm on Tuesday if you'd like anything amended.

### CODE REVIEW

**Review by AshGDS — COMMENTED** [review]
Thanks @gtvj - what are your thoughts on mentioning the developer's responsibility to continuously accessibility test their code while developing, for example:

- Testing with WAVE
- Testing with headingsMap
- Testing keyboard navigation testing
- Testing with Chrome Lighthouse

I'm aware this might fall under your progressive enhancement sentence so feel free to ignore this!

**Comment by gtvj** [comment]
Thanks @AshTNA - I'd intended this to be reflected by the statement about following the development guide but have added an explicit point in the `README.md`. I'm not keen on specifying how testing should take place because it will duplicate what's in the guide.

**Review by AshGDS — APPROVED** [review]
Thanks @gtvj :+1:

**Comment by gtvj** [comment]
Merging this now.

**Pull request merged**
